### ISSUE TITLE
App Library Controller

### ISSUE THREAD

**Issue by KeyFlyz** [tomaszpoliszuk/AppLibraryController#1]
App Library Controller working great.
XS Max IOS 14.3 
unc0ver v6.1.1

**Comment by tomaszpoliszuk** [comment]
Could you provide more info - so far nobody told me about such issue and didn't experienced it myself.

Please also try to disable other tweaks and then check again (maybe you have another tweak that also disables App Library?)

**Comment by KeyFlyz** [comment]
I don't have anymore info unfortunately there's no crash App Library is just gone even with the tweak uninstalled but I can access the App Library in a non jailbroken state and when you respring in App Library settings after reset settings it causes a respring loop. I have no other springboard tweaks other than snowboard and I know that's not causing it I've tried uicache and ldrestart but nothing works I've done give up at this point of fixing it.

**Comment by KeyFlyz** [comment]
Just figured it out it was PrimalFolders2 causing the issue App Library just wanted to let you know. It's working again now. So sorry.

**Comment by tomaszpoliszuk** [comment]
What happened here?

Did you fixed this issue?

**Comment by KeyFlyz** [comment]
Yes you were correct the issue was with another tweak wich was installed after App Library Controller— primal folders 2 I didn’t realize that it had a disable App Library disable option wich was on by default so sorry App Library Controller Works great.

Sent from my iPhone

On Mar 19, 2021, at 4:51 PM, Tomasz Poliszuk ***@***.***> wrote:

﻿

What happened here?

Did you fixed this issue?

**Comment by tomaszpoliszuk** [comment]
Awesome!
I'm closing this issue then.

Have a nice day!
