### ISSUE TITLE
Keyboard overlaid by menu

### ISSUE THREAD

**Issue by ghost** [tomaszpoliszuk/AppLibraryController#2]
iPhone X, iOS 14.4, Checkra1n 12.2.

When using the search field, the keyboard is overlaid by the menu.
![F0923C56-AC01-42D8-A924-8094EF2EBCCB](https://user-images.githubusercontent.com/48016167/112753707-3dd57d80-9035-11eb-8891-e62f7c897301.png)

**Comment by tomaszpoliszuk** [comment]
Could you try disabling other tweaks to check if it's not issue connected to usage of other tweak?

**Comment by tomaszpoliszuk** [comment]
Closed due to lack of response.
