### ISSUE TITLE
Exiting App Library crashes SpringBoard

### ISSUE THREAD

**Issue by ghost** [tomaszpoliszuk/AppLibraryController#4]
**Device:**
iPhone 7

**iOS version:**
14.5.1

**Jailbreak:**
odysseyra1n (Procursus Bootstrap, libhooker)

**Issue:**
When I exit the App Library either by pressing the home button or by swiping left, my SpringBoard crashes. No crash report appears in cr4shed. I tried disabling all tweaks in SpringBoard (throught libhooker configurator) but App Library Controller to no avail. ReSpring, ldrestart and full reboot + rejailbreak didn't change a thing.

**Comment by tomaszpoliszuk** [comment]
Yeah - I know (but thank you for reporting) :)
Already have it fixed but have additional visual glitch - if i won't figure it out until tomorrow I'll release it as hotfix (better visual glitch than crash).

Have a nice day!

**Comment by ghost** [comment]
Oh I see, good luck fixing the glitch 🤞

**Comment by tomaszpoliszuk** [comment]
Didn't had time to find fix yet so I've submitted update to BigBoss repo - you can download and install .deb file (before it's published on BigBoss repo) from here -> [version 1.3.2](https://github.com/tomaszpoliszuk/AppLibraryController/releases/tag/1.3.2)
