### ISSUE TITLE
Animation to close App Library is bugged

### ISSUE THREAD

**Issue by machineonamission** [tomaszpoliszuk/AppLibraryController#7]
Possible duplicate of #5 though I'm on iOS 14.3

Without tweak installed

![without tweak installed](https://user-images.githubusercontent.com/35177464/126879365-24e8ea70-f4f6-4eac-b587-6a172db17263.MOV)

With tweak installed

![with tweak installed](https://user-images.githubusercontent.com/35177464/126879373-ea5969ec-f890-4f13-ad11-e4fcd25ed44a.MOV)

Reproduced on iOS 14.3 and iPadOS 14.2 both with tweak version 1.4 under taurine/libhooker

**Comment by tomaszpoliszuk** [comment]
You mean it's faster than without tweak?

It's probably side-effect from workaround for "Alphabetic List only" mode - if it's that I will disable that part of code for "Enabled" mode.

That #5 issue was another problem (App Library wasn't fully swiping off screen and then it was disappearing).

**Comment by tomaszpoliszuk** [comment]
Fixed in latest update.
