### ISSUE TITLE
Hi glitches in iPad os 14.5 with iPad Air 4

### ISSUE THREAD

**Issue by vink2212** [tomaszpoliszuk/AppLibraryController#8]
https://user-images.githubusercontent.com/62817618/139840500-8b256b58-0de5-4cde-8085-439a0ea24f4d.mov

Just jailbroken with the new u0 7.0.2 update and installed this tweak. It works for the most part but the actual App Library seems to be glitched in both portrait and landscape mode

**Comment by tomaszpoliszuk** [comment]
If you referring to it displaying only on left half of screen then that's intended (for now) behavior (it's less buggy than enabling it on full screen).
If not please tell me more.

**Comment by tomaszpoliszuk** [comment]
Closed due to lack of response.
